\echo === Operation ===
SELECT * FROM Operation;
\echo === ClientService ===
SELECT * FROM ClientService;
\echo === Account ===
SELECT * FROM Account;
\echo === Service ===
SELECT * FROM Service;
\echo === ServiceType ===
SELECT * FROM ServiceType;
\echo === Client ===
SELECT * FROM Client;