\echo === Operation ===
SELECT * FROM Operation;
\echo === Subscription ===
SELECT * FROM Subscription;
\echo === Account ===
SELECT * FROM Account;
\echo === Service ===
SELECT * FROM Service;
\echo === ServiceType ===
SELECT * FROM ServiceType;
\echo === Client ===
SELECT * FROM Client;
